version: '3.9'
services:
  app:
    depends_on:
      - mongo
    links:
      - mongo
    # If you need to connect to your db from outside this container
#    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    expose:
      - 8000
    ports:
      - 8000:8000
    networks:
      - custommer-app-db-network
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ./data/db:/data/db
    networks:
      - custommer-app-db-network
networks:
  custommer-app-db-network: